import type { Spot } from "./types";

export const SPOTS: Spot[] = [
  {
    id: 1,
    name: "Phở Bò 36",
    category: "Vietnamese",
    emoji: "🍜",
    accent: "#ED1B24",
    lat: 10.897,
    lon: 106.772,
    rating: 4.9,
    reviewCount: 312,
    priceLevel: 2,
    isOpen: true,
    closesAt: "11 PM",
    distance: "0.3 km",
    img: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=600&h=400&fit=crop",
    description:
      "Classic northern-style pho with slow-cooked bone broth, hand-cut rice noodles, and fresh herb plates.",
    tags: ["Noodles", "Authentic", "Local Fav"],
  },
  {
    id: 2,
    name: "Matcha Room",
    category: "Cafe",
    emoji: "🍵",
    accent: "#2A9D8F",
    lat: 10.901,
    lon: 106.769,
    rating: 4.7,
    reviewCount: 198,
    priceLevel: 2,
    isOpen: true,
    closesAt: "10 PM",
    distance: "0.6 km",
    img: "https://images.unsplash.com/photo-1582787895088-2ff176b668d2?w=600&h=400&fit=crop",
    description:
      "Japanese-inspired specialty cafe with premium ceremonial-grade matcha, aesthetic interiors, and calm vibes.",
    tags: ["Matcha", "Aesthetic", "Chill"],
  },
  {
    id: 3,
    name: "Neon Ramen House",
    category: "Ramen",
    emoji: "🍜",
    accent: "#F97316",
    lat: 10.895,
    lon: 106.778,
    rating: 4.8,
    reviewCount: 254,
    priceLevel: 2,
    isOpen: true,
    closesAt: "11:30 PM",
    distance: "0.9 km",
    img: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&h=400&fit=crop",
    description:
      "Tonkotsu heaven. Rich 18-hour broth, perfectly tender chashu, and that addictive neon-lit atmosphere.",
    tags: ["Ramen", "Japanese", "Late Night"],
  },
  {
    id: 4,
    name: "BBQ Midnight",
    category: "BBQ",
    emoji: "🍖",
    accent: "#E76F51",
    lat: 10.903,
    lon: 106.774,
    rating: 4.5,
    reviewCount: 176,
    priceLevel: 3,
    isOpen: true,
    closesAt: "1 AM",
    distance: "1.1 km",
    img: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&h=400&fit=crop",
    description:
      "Open-fire charcoal BBQ with premium wagyu cuts, live acoustic music, and outdoor seating under the stars.",
    tags: ["BBQ", "Late Night", "Wagyu"],
  },
  {
    id: 5,
    name: "Bánh Mì Cô Ba",
    category: "Street Food",
    emoji: "🥖",
    accent: "#F59E0B",
    lat: 10.899,
    lon: 106.77,
    rating: 4.6,
    reviewCount: 430,
    priceLevel: 1,
    isOpen: true,
    closesAt: "7 PM",
    distance: "0.2 km",
    img: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&h=400&fit=crop",
    description:
      "Legendary 30-year-old street stall. Crispy baguette with pâté, house-made pickled daikon, and signature chilli sauce.",
    tags: ["Bánh Mì", "Quick Bite", "Iconic"],
  },
  {
    id: 6,
    name: "Chè Ngon Lắm",
    category: "Dessert",
    emoji: "🍮",
    accent: "#A855F7",
    lat: 10.893,
    lon: 106.775,
    rating: 4.4,
    reviewCount: 142,
    priceLevel: 1,
    isOpen: true,
    closesAt: "9 PM",
    distance: "0.7 km",
    img: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&h=400&fit=crop",
    description:
      "Seven-layer dessert bar serving traditional chè ba màu, taro soup, and seasonal coconut-based sweets.",
    tags: ["Dessert", "Sweet", "Traditional"],
  },
  {
    id: 7,
    name: "Hidden Cafe Rooftop",
    category: "Cafe",
    emoji: "☕",
    accent: "#ff6b35",
    lat: 10.906,
    lon: 106.767,
    rating: 4.6,
    reviewCount: 89,
    priceLevel: 3,
    isOpen: true,
    closesAt: "10 PM",
    distance: "1.3 km",
    img: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&h=400&fit=crop",
    description:
      "Secret rooftop with panoramic city views, single-origin pour-overs, and a menu that changes weekly.",
    tags: ["Hidden Gem", "Specialty", "View"],
  },
  {
    id: 8,
    name: "Hủ Tiếu Chú Sáu",
    category: "Vietnamese",
    emoji: "🍜",
    accent: "#EC4899",
    lat: 10.892,
    lon: 106.78,
    rating: 4.9,
    reviewCount: 521,
    priceLevel: 1,
    isOpen: false,
    closesAt: "2 PM",
    distance: "1.0 km",
    img: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&h=400&fit=crop",
    description:
      "Dawn-to-noon only. The most sought-after dry hủ tiếu in the city — silky noodles, crispy pork cracklings, rich broth.",
    tags: ["Breakfast", "Iconic", "Cash Only"],
  },
  {
    id: 9,
    name: "Sushi Yuki",
    category: "Japanese",
    emoji: "🍣",
    accent: "#3B82F6",
    lat: 10.908,
    lon: 106.771,
    rating: 4.7,
    reviewCount: 167,
    priceLevel: 3,
    isOpen: true,
    closesAt: "10:30 PM",
    distance: "1.5 km",
    img: "https://images.unsplash.com/photo-1514361892635-6b07e31e75f9?w=600&h=400&fit=crop",
    description:
      "Intimate 14-seat omakase counter. Chef Yuki sources daily from Tsukiji market to deliver an authentic Tokyo experience.",
    tags: ["Omakase", "Premium", "Reservation"],
  },
  {
    id: 10,
    name: "Bún Riêu Cua Đồng",
    category: "Vietnamese",
    emoji: "🦀",
    accent: "#10B981",
    lat: 10.896,
    lon: 106.783,
    rating: 4.8,
    reviewCount: 287,
    priceLevel: 1,
    isOpen: true,
    closesAt: "6 PM",
    distance: "0.8 km",
    img: "https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=600&h=400&fit=crop",
    description:
      "Tangy tomato-based crab broth with hand-pounded fresh crab paste, vermicelli, and fried tofu puffs.",
    tags: ["Noodles", "Crab", "Morning Only"],
  },
  {
    id: 11,
    name: "Coffee Blend Lab",
    category: "Cafe",
    emoji: "🧪",
    accent: "#8B5CF6",
    lat: 10.904,
    lon: 106.776,
    rating: 4.5,
    reviewCount: 93,
    priceLevel: 2,
    isOpen: true,
    closesAt: "9 PM",
    distance: "1.2 km",
    img: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=600&h=400&fit=crop",
    description:
      "Lab-style specialty roastery. Rotating origin selection, cold brew on nitro tap, and monthly cupping events.",
    tags: ["Specialty", "Lab", "Pour-Over"],
  },
  {
    id: 12,
    name: "Nem Nướng Cuốn",
    category: "Street Food",
    emoji: "🌯",
    accent: "#F97316",
    lat: 10.898,
    lon: 106.768,
    rating: 4.3,
    reviewCount: 204,
    priceLevel: 1,
    isOpen: true,
    closesAt: "8 PM",
    distance: "0.4 km",
    img: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&h=400&fit=crop",
    description:
      "DIY roll-your-own station — grilled pork skewers, fresh herbs, rice paper, and three house dipping sauces.",
    tags: ["Street Food", "DIY", "Fun"],
  },
];

export const CATEGORIES = [
  "All",
  "Vietnamese",
  "Cafe",
  "Ramen",
  "Street Food",
  "BBQ",
  "Dessert",
  "Japanese",
] as const;

export const PRICE_ICONS = ["", "💰", "💰💰", "💰💰💰"] as const;
