"""Add media fields to GroupChatMessage

Revision ID: 188aa48b49c8
Revises: 9c256869b983
Create Date: 2026-04-20 23:46:47.368466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '188aa48b49c8'
down_revision: Union[str, Sequence[str], None] = '9c256869b983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_chat_messages', sa.Column('content_type', sa.String(length=20), nullable=False, server_default='text'))
    op.add_column('group_chat_messages', sa.Column('media_url', sa.String(length=500), nullable=True))
    op.add_column('group_chat_messages', sa.Column('media_meta', sa.JSON(), nullable=False, server_default='{}'))
    op.alter_column('group_chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_group_chat_messages_content_type'), 'group_chat_messages', ['content_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_chat_messages_content_type'), table_name='group_chat_messages')
    op.alter_column('group_chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('group_chat_messages', 'media_meta')
    op.drop_column('group_chat_messages', 'media_url')
    op.drop_column('group_chat_messages', 'content_type')
    # ### end Alembic commands ###
