"""Add parent_id to comments

Revision ID: 24073ac4150e
Revises: 6f4b0f8f2a1d
Create Date: 2026-04-24 15:12:17.000848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24073ac4150e'
down_revision: Union[str, Sequence[str], None] = '6f4b0f8f2a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.alter_column('chat_messages', 'media_meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_locations_category'), table_name='locations')
    op.drop_index(op.f('idx_locations_category_id'), table_name='locations')
    op.drop_index(op.f('idx_locations_lat_lng'), table_name='locations')
    op.drop_constraint(op.f('uq_message_user_emoji'), 'message_reactions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_message_user_emoji'), 'message_reactions', ['message_id', 'user_id', 'emoji'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_locations_lat_lng'), 'locations', ['lat', 'lng'], unique=False)
    op.create_index(op.f('idx_locations_category_id'), 'locations', ['category', 'id'], unique=False)
    op.create_index(op.f('idx_locations_category'), 'locations', ['category'], unique=False)
    op.alter_column('chat_messages', 'media_meta',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    # ### end Alembic commands ###
