"""Add Badge System schema

Revision ID: 808c5d2b84dc
Revises: d1e2f3a4b5c6
Create Date: 2026-04-17 15:57:05.858142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.

revision: str = '808c5d2b84dc'
down_revision: Union[str, Sequence[str], None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add new columns as NULLABLE first (to handle existing rows)
    op.add_column('badges', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('badges', sa.Column('icon_name', sa.String(length=50), nullable=True))
    op.add_column('badges', sa.Column('rarity', sa.String(length=20), nullable=True))
    op.add_column('badges', sa.Column('accent_color', sa.String(length=20), nullable=True))
    op.add_column('badges', sa.Column('is_hidden', sa.Boolean(), nullable=True))

    # Step 2: Populate new columns from old columns / defaults
    op.execute("UPDATE badges SET name = label WHERE name IS NULL")
    op.execute("UPDATE badges SET icon_name = COALESCE(NULLIF(icon, ''), 'trophy') WHERE icon_name IS NULL")
    op.execute("UPDATE badges SET rarity = 'Common' WHERE rarity IS NULL")
    op.execute("UPDATE badges SET accent_color = COALESCE(NULLIF(color, ''), '#007AFF') WHERE accent_color IS NULL")
    op.execute("UPDATE badges SET is_hidden = false WHERE is_hidden IS NULL")

    # Step 3: Now make columns NOT NULL
    op.alter_column('badges', 'name', nullable=False)
    op.alter_column('badges', 'icon_name', nullable=False)
    op.alter_column('badges', 'rarity', nullable=False)
    op.alter_column('badges', 'accent_color', nullable=False)
    op.alter_column('badges', 'is_hidden', nullable=False)

    # Step 4: Alter description type
    op.alter_column('badges', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    # Step 5: Drop old columns
    op.drop_column('badges', 'label')
    op.drop_column('badges', 'color')
    op.drop_column('badges', 'icon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badges', sa.Column('icon', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('badges', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('badges', sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('badges', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('badges', 'is_hidden')
    op.drop_column('badges', 'accent_color')
    op.drop_column('badges', 'rarity')
    op.drop_column('badges', 'icon_name')
    op.drop_column('badges', 'name')
    # ### end Alembic commands ###
