"""Add Badge System schema

Revision ID: 808c5d2b84dc
Revises: d1e2f3a4b5c6
Create Date: 2026-04-17 15:57:05.858142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.

revision: str = '808c5d2b84dc'
down_revision: Union[str, Sequence[str], None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badges', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('badges', sa.Column('icon_name', sa.String(length=50), nullable=False))
    op.add_column('badges', sa.Column('rarity', sa.String(length=20), nullable=False))
    op.add_column('badges', sa.Column('accent_color', sa.String(length=20), nullable=False))
    op.add_column('badges', sa.Column('is_hidden', sa.Boolean(), nullable=False))
    op.alter_column('badges', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('badges', 'label')
    op.drop_column('badges', 'color')
    op.drop_column('badges', 'icon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badges', sa.Column('icon', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('badges', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('badges', sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('badges', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('badges', 'is_hidden')
    op.drop_column('badges', 'accent_color')
    op.drop_column('badges', 'rarity')
    op.drop_column('badges', 'icon_name')
    op.drop_column('badges', 'name')
    # ### end Alembic commands ###
