"""add_default_vectors

Revision ID: f9c9ee2699c2
Revises: 8b66a71fd32b
Create Date: 2026-03-22 10:41:27.117065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'f9c9ee2699c2'
down_revision: Union[str, Sequence[str], None] = '8b66a71fd32b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Trước tiên, cập nhật các row hiện tại có vector null → [0.5]*15
    default_vec = '[' + ','.join(['0.5'] * 15) + ']'
    op.execute(f"UPDATE users SET food_vector = '{default_vec}' WHERE food_vector IS NULL")
    op.execute(f"UPDATE users SET place_vector = '{default_vec}' WHERE place_vector IS NULL")
    
    # Sau đó mới alter column nullable=False
    op.alter_column('users', 'food_vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=15),
               nullable=False)
    op.alter_column('users', 'place_vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=15),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'place_vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=15),
               nullable=True)
    op.alter_column('users', 'food_vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=15),
               nullable=True)
    # ### end Alembic commands ###
